jobs:
  lint_package_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm lint:package-json

name: Lint Package JSON

on:
  pull_request: ~
  push:
    branches:
      - main
